
ALTER TABLE sys_user
  ADD COLUMN upline_id BIGINT NULL DEFAULT NULL,
  ADD COLUMN sba_id    BIGINT NULL DEFAULT NULL,
  ADD COLUMN cpy_id    BIGINT NULL DEFAULT NULL,
  ADD COLUMN is_sub TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'is sub account',
  DROP COLUMN parent_id;



